# Generated by Django 3.2 on 2021-05-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('year_of_warranty', models.PositiveBigIntegerField(default=1)),
                ('finance_plan', models.CharField(default='unavailable', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='carspec',
            name='car_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.carplan'),
        ),
    ]
