# Generated by Django 3.2 on 2021-05-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210519_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspec',
            name='car_brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carspec',
            name='car_model',
            field=models.CharField(max_length=100),
        ),
    ]
